# SPECIES, = glob_wildcards("../results/{species}.fa.gz")
import pandas as pd
SPECIES = pd.read_csv("../resources/drosophila_urls.csv", names=["organism", "url"]).organism

rule all:
    input:
        # "../results/drosophila_melanogaster_cds.fa"
        expand("../results/{species}_filtered.fa", species=SPECIES)

rule download_genomes:
    input:  "../resources/drosophila_urls.csv"
    output: expand("../resources/genomes/{species}.fa.gz", species=SPECIES)
    shell:
        """
        scripts/download_ncbi_genomes.py --list {input} --folder ../resources/genomes/
        """


rule decompress_genomes:
    input:  "../resources/genomes/{species}.fa.gz"
    output: temp("../results/{species}.fa")
    shell:
        """
        gunzip -c {input} > {output}
        """


rule get_longest_isoform:
    input:  "../results/{species}.fa"
    output: "../results/{species}_filtered.fa"
    shell:
        """
        ./scripts/get_longest_isoform.py -s {input} > {output}
        """
