# SPECIES, = glob_wildcards("../results/{species}.fa.gz")
import pandas as pd
SPECIES = pd.read_csv("../resources/drosophila_urls.csv", names=["organism", "url"]).organism

rule all:
    input:
        expand("../results/{species}_filt.fna", species=SPECIES),
        directory("../results/evolutionary_rates/")


rule download_genomes:
    input:  "../resources/drosophila_urls.csv"
    output: expand("../resources/genomes/{species}.fa.gz", species=SPECIES)
    shell:
        """
        scripts/download_ncbi_genomes.py --list {input} --folder ../resources/genomes/
        """


rule decompress_genomes:
    input:  "../resources/genomes/{species}.fa.gz"
    output: temp("../results/{species}.fa")
    shell:
        """
        gunzip -c {input} > {output}
        """


rule get_longest_isoform:
    input:  "../results/{species}.fa"
    output: "../results/{species}_filt.fna",
    # output: "../results/{species}_filt.faa",
    #         "../results/{species}_filt.fna"
    shell:
        """
        ./scripts/get_longest_isoform.py -s {input} -o {wildcards.species} && \
        mv *filt.fna ../results/
        """


rule extract_orthgroup_multifasta:
    input: expand("../results/{species}_filt.fna", species=SPECIES)
    params: "../results/evolutionary_rates/"
    output: directory("../results/evolutionary_rates/")
    shell:
        """
        cat {input} > sequences.fna && \
        mkdir {params} && \
        scripts/extract_orthogroups.py -o ../resources/Orthogroups.tsv -s sequences.fna -d {params} && \
        rm sequences.fna
        """


# rule run_orthofinder:
#     input: expand("../results/{species}_filt.faa", species=SPECIES)
#     output: directory("../results/orthofinder_run/")
#     params: "../results/orthofinder_run"
#     shell:
#         """
#         mkdir {params} && \
#         mv {input} {params} && \
#         orthofinder -f {params}
#         """
